name: shelf_form_validator
description: A lightweight, extensible validation framework for Dart form data. Ideal for backend or CLI apps.
version: 0.1.0
repository: https://github.com/your_username/shelf_form_validator

environment:
  sdk: ^3.7.2

dependencies:
  # No runtime dependencies

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0